site_name: Wordcab Posts
site_url: https://wordcab.github.io/wordcab-posts/

copyright: Copyright &copy; 2023 Wordcab team.
edit_uri: edit/main/docs/
repo_url: https://github.com/Wordcab/wordcab-posts
repo_name: Wordcab/wordcab-posts

theme:
  name: material
  language: en
  logo: assets/images/wordcab-favicon.png
  favicon: assets/images/favicon.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil-plus
    view: material/eye
  features:
    - content.action.edit
    - content.tabs.link
    - navigation.footer
    - navigation.path
    - navigation.prune
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    

plugins:
  - blog
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - git-committers:
      repository: Wordcab/wordcab-posts
      branch: main
  - privacy:
      enabled: !ENV [CI, false]
  - search:
      lang: en
  - social:
      cards: !ENV [CARDS, false]
  - termynal

nav:
  - 👋 Welcome Home: index.md
  - 💬 Blog: blog/index.md

markdown_extensions:
  - admonition
  - codehilite
  - extra
  - toc:
      permalink: true

extra:
  analytics:
    provider: google
    property: G-196126008
    feedback:
      title: Was this page informative?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by telling us what was wrong at **info@wordcab.com**
  consent:
    title: Cookies
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Wordcab
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/wordcab
